[workspace]
resolver = "2"
members = [
  "crates/sure-syntax",
  "crates/sure-check",
  "crates/sure-fmc",
  "crates/sure-emit",
  "crates/surec",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.80"
license = "MIT"

[workspace.dependencies]
sure-syntax = { path = "crates/sure-syntax" }
sure-check = { path = "crates/sure-check" }
sure-fmc = { path = "crates/sure-fmc" }
sure-emit = { path = "crates/sure-emit" }

[workspace.lints.rust]
unsafe_code = "forbid"
